FROM quay.io/rhdevelopers/tutorial-tools:0.0.3

# set up the nexus repo locally so that each build is faster
# check the nexus deployment in $PROJECT_HOME/k8s/nexus.yaml

ENV MAVEN_MIRROR_URL http://192.168.64.1:8081/nexus/content/groups/public/

# make the project directory

RUN mkdir -p /workspace/skaffold-quarkus-helloworld

# The default user of tutorial tools is with id 10001, make sure the files
# are owned by the developer user for sync to happen

COPY --chown=10001 src /workspace/skaffold-quarkus-helloworld/src

COPY --chown=10001 pom.xml /workspace/skaffold-quarkus-helloworld/

WORKDIR /workspace/skaffold-quarkus-helloworld

CMD [ "mvn","clean","compile", "quarkus:dev" ]