= Skaffold Quarkus Hello World
:experimental:

A demo to show how to use https://https://skaffold.dev/[Skaffold] with https://quarkus.io[Quarkus] developer mode to enable rapid Java application with Kubernetes.

== Pre-requisites

* https://kubernetes.io/docs/setup/learning-environment/minikube/[minikube]
* http://openjdk.java.net/install/[Java 8]
* https://maven.apache.org[Apache Maven]
* https://https://skaffold.dev/[Skaffold]
* https://www.docker.com/products/docker-desktop[Docker]

== Setup Kubernetes Cluster

[source,bash]
----
minikube profile quarkus-demos
minikube start -p quarkus-demos --memory=8192 --cpus=4 --disk-size=50g #<1>
----

<1> Please add the other needed options as per your operating system

== Setup Nexus

We will use nexus for caching maven artifacts so that builds are faster.

[source,bash]
----
kubectl apply -f k8s/nexus.yaml
----

Wait for some time to have nexus initialize and run. You can watch the status via `kubectl get pods -w `, use kbd:[Ctrl+c] to terminate the watch

== Run Skaffold

[source,bash]
----
skaffold dev --port-forward #<1>
----
<1> Run skaffold in `dev` mode. The **port-forward** option automatically foward the kubernetes service port(default is 8080) to localhost port (default is 8080). By default it maps the application service port `8080` to host `8080`

[NOTE]
====
* The first build will be bit slower as it needs to cache the artifacts in nexus maven repository
* You can watch the status via `kubectl get pods -w `, use kbd:[Ctrl+c] to terminate the watch
====

Once you see your application running, something like 

[source,bash]
----

----

Try opening the url http://locahost:8080/hello, which should show a message like **Welcome to Quarkus!!** from the link:./src/main/java/com/redhat/developers/GreetingResource.java#L14[GreetingResource.java]

Now make any changes to the sources in your editor, and try refreshing the browser you will see Quarkus live reload in action without application(pod) redeploy.

[TIP]
====
Though the demo application provides `build.cmd` for windows users I personally recommend https://docs.microsoft.com/en-us/windows/wsl/install-win10[WSL] and https://code.visualstudio.com/docs/remote/remote-overview[VS Code Remote Development]
====
